name: Run Dextools Monitor

on:
  workflow_dispatch:   # 👈 ESTO crea el botón manual

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Instalar navegadores Playwright
        run: npx playwright install --with-deps

      - name: Ejecutar script
        run: node index.js
