name: Playwright Tests
on:
  schedule:
    - cron: '15 * * * *'  # minuto 15 de cada hora
    - cron: '45 * * * *'  # minuto 45 de cada hora
  workflow_dispatch:       # permite ejecutar manualmente

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar tests Playwright
        run: npx playwright test

      - name: Guardar reportes y capturas
        uses: actions/upload-artifact@v3
        with:
          name: reportes-playwright
          path: |
            playwright-report
            test-results
            screenshots            
